# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30




name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Node.js (use 16.x or 18.x if needed)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # You can change this to '14.x', '16.x', or '18.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Install Playwright (includes browser dependencies)
    - name: Install Playwright
      run: npx playwright install --with-deps

    # Step 5: Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test

    # Step 6: Upload Playwright test report
    - name: Upload Playwright report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
